[package]
name = "poke-gol-rewrite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.29.4"
wgpu = "0.18.0"
env_logger = "0.10.1"
log = "0.4.20"
rand = "0.8.5"
owo-colors = "3.5.0"
